
INSERT INTO user (username, password, first_name, last_name, position, seniority) VALUES ('terry','demo','Terry', 'Fuzz', 'DEV', 'SENIOR');
INSERT INTO user (username, password, first_name, last_name, position, seniority) VALUES ('john','demo','John', 'Fizz', 'LEAD DEV', 'SENIOR');
INSERT INTO user (username, password, first_name, last_name, position, seniority) VALUES ('bob','demo','Bob', 'Doe', 'Auditor', 'JUNIOR');
INSERT INTO user (username, password, first_name, last_name, position, seniority) VALUES ('alice','demo','Alice', 'Bar', 'Associate', 'MANAGER');

INSERT INTO asset_type (type_name) VALUES ('laptop');
INSERT INTO asset_type (type_name) VALUES ('charger');
INSERT INTO asset_type (type_name) VALUES ('screen');

INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 0', 1, 1, 'ZfmjldRmqk');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 1', 1, 1, 'ZjRrqJDrIz');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 2', 1, 1, 'eEMfxOhPBG');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 3', 1, 1, 'QcJbHKaPAZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 4', 1, 1, 'MRgSuwKHfc');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 5', 1, 1, 'DbJouvTjJC');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 6', 1, 1, 'PnoaNlmMXF');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 7', 1, 1, 'tYqfIYpYDB');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 8', 1, 1, 'oTEGkpYygc');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 9', 1, 1, 'zzTWQIWSlj');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 10', 1, 1, 'IshqXkecae');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 11', 1, 1, 'qrBvCqKkux');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 12', 1, 1, 'getfJNiHVs');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 13', 1, 1, 'mREVHxxPHM');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 14', 1, 1, 'phGlGJKABN');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 15', 1, 1, 'OlhXmlckFm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 16', 1, 1, 'KTzqYQAWjq');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 17', 1, 1, 'bLNMYlgKFQ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 18', 1, 1, 'JzDdAWFvnx');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 19', 1, 1, 'hulYeLeSJe');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 20', 1, 1, 'MPaheCmKty');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 21', 1, 1, 'VFIprfqJbs');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 22', 1, 1, 'puOYUoKYnJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 23', 1, 1, 'EBnLdkWcjh');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 24', 1, 1, 'igNBAJMTor');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 25', 1, 1, 'whXGRRBPUX');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 26', 1, 1, 'jqvuURFmyJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 27', 1, 1, 'NOxqkuzWRe');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 28', 1, 1, 'vccekppsRv');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 29', 1, 1, 'UlhvGOtYUm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 30', 1, 1, 'emEDelLJDr');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 31', 1, 1, 'yqVRRxHQUP');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 32', 1, 1, 'NKfFHMzpbO');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 33', 1, 1, 'Xwfkzwfrhv');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 34', 1, 1, 'WVpScFAHFI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 35', 1, 1, 'CJlRPdqxVE');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 36', 1, 1, 'hKUYlzgVND');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 37', 1, 1, 'kZcyPPctya');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 38', 1, 1, 'lUxvokAVQm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 39', 1, 1, 'iceIatKDWF');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 40', 1, 1, 'ztrPiNDnhk');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 41', 1, 1, 'EWpabkfEuN');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 42', 1, 1, 'VTUQUJxAfc');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 43', 1, 1, 'HJPpYAuAEo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 44', 1, 1, 'qsEWrFGcSZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 45', 1, 1, 'WTxTRqRUBk');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 46', 1, 1, 'MgVBRByJUJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 47', 1, 1, 'eaypQmriaI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 48', 1, 1, 'DEKrSpjdQA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 49', 1, 1, 'VZuTfPwyuw');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 50', 1, 1, 'UFxvenWetM');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 51', 1, 1, 'DIkxzFoefR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 52', 1, 1, 'vFcoDgkpCW');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 53', 1, 1, 'aQFQVxXmKP');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 54', 1, 1, 'xTtGsOhQsF');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 55', 1, 1, 'cJxXPbppYU');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 56', 1, 1, 'vcnKibjnoO');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 57', 1, 1, 'qPtuzPzZem');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 58', 1, 1, 'AJvzCUIrQK');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 59', 1, 1, 'yLgNgdPAuU');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 60', 1, 1, 'WWGNRrbZra');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 61', 1, 1, 'ukfXjsJNxA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 62', 1, 1, 'lIojHApwms');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 63', 1, 1, 'GcLLqgQykW');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 64', 1, 1, 'vIxPcooRWf');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 65', 1, 1, 'MiiuavHJnN');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 66', 1, 1, 'NBEtAdywbp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 67', 1, 1, 'TOYQAtXvls');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 68', 1, 1, 'lNIHlfvDvk');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 69', 1, 1, 'siySYMhWuQ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 70', 1, 1, 'EqtYtLucBR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 71', 1, 1, 'DFOSWLCFnV');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 72', 1, 1, 'NfyQlKZKqP');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 73', 1, 1, 'hwrZFiTtKy');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 74', 1, 1, 'GmGZUoVhTF');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 75', 1, 1, 'TDkcaXgJwe');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 76', 1, 1, 'CQinWlckjN');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 77', 1, 1, 'RDGRZoJUrW');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 78', 1, 1, 'NbIhRCtHIT');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 79', 1, 1, 'tKNypnBQnC');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 80', 1, 1, 'gTTNHsdVIe');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 81', 1, 1, 'RpTleDIAlp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 82', 1, 1, 'qiDcjjqZyu');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 83', 1, 1, 'YhdhpVTfsc');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 84', 1, 1, 'eTjgbnVSvt');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 85', 1, 1, 'JNnLqsJvWl');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 86', 1, 1, 'dUhIyRFRjR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 87', 1, 1, 'aimnAmwPkm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 88', 1, 1, 'KvsAnNhJBs');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 89', 1, 1, 'lcgAZEcqWW');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 90', 1, 1, 'OEnbwAVZrw');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 91', 1, 1, 'fCBAGKDGlJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 92', 1, 1, 'BxXcELaeZm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 93', 1, 1, 'wvPVBvxjuP');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 94', 1, 1, 'VgFOXRnMam');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 95', 1, 1, 'lEFgFQDOmg');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 96', 1, 1, 'UewhJqGhmU');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 97', 1, 1, 'DqZgIbVxwA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 98', 1, 1, 'mQTEOulDTv');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Laptop MacBook Air 99', 1, 1, 'dkYPbufQET');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 0', 1, 2, 'uUFrGGFrci');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 1', 1, 2, 'CXkNHJDtMX');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 2', 1, 2, 'NVbkfMnvkG');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 3', 1, 2, 'XbCIZmWUuu');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 4', 1, 2, 'LctBYJcRGA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 5', 1, 2, 'brgJyImtzI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 6', 1, 2, 'hWQDtFFLLk');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 7', 1, 2, 'pgSyCPRHWv');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 8', 1, 2, 'JTdnJTiMzf');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 9', 1, 2, 'rQwJGGPpxJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 10', 1, 2, 'UUKhMKPoED');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 11', 1, 2, 'YdjEWYXzTD');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 12', 1, 2, 'JCeWaIDEVJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 13', 1, 2, 'PznkaCCNtI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 14', 1, 2, 'vZGGfZGPPR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 15', 1, 2, 'qKXvijPibC');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 16', 1, 2, 'PwAxQADdRN');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 17', 1, 2, 'IFsLzFhBhd');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 18', 1, 2, 'hOdMQSyQkR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 19', 1, 2, 'YtpGvRMzVF');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 20', 1, 2, 'TslSRFXcTm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 21', 1, 2, 'OaEAZDGRFK');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 22', 1, 2, 'lKZRzqEvbU');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 23', 1, 2, 'NUhBAQGyvr');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 24', 1, 2, 'LuEzrUbUgZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 25', 1, 2, 'XWSfEeVUFb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 26', 1, 2, 'cCNhGXAnRL');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 27', 1, 2, 'rTQuxXXmih');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 28', 1, 2, 'ftgKfLuoKo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 29', 1, 2, 'XDaivDMPNs');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 30', 1, 2, 'QrAFqaeaew');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 31', 1, 2, 'iouHuKagYy');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 32', 1, 2, 'eFzBPQHmax');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 33', 1, 2, 'OnmFABNAPN');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 34', 1, 2, 'SNNxsVtPUB');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 35', 1, 2, 'cPKbJeoqsY');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 36', 1, 2, 'kTDdXyyWLu');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 37', 1, 2, 'mLkGknoflb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 38', 1, 2, 'pvxZYxDGfZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 39', 1, 2, 'aooMWzRrLV');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 40', 1, 2, 'GJmRchWMKm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 41', 1, 2, 'dsaZtqsACo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 42', 1, 2, 'KOyYxLtwpQ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 43', 1, 2, 'HihtSSzCwJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 44', 1, 2, 'BTDeByKdzb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 45', 1, 2, 'mveOVZdBBA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 46', 1, 2, 'McgLCakIPy');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 47', 1, 2, 'xcFvkXvmQp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 48', 1, 2, 'RpFhJOlKAX');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 49', 1, 2, 'IrwBcZZGQp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 50', 1, 2, 'mQTflpRKXb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 51', 1, 2, 'meRrvGScPq');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 52', 1, 2, 'mqBZdQmoPZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 53', 1, 2, 'gutsJjcqoS');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 54', 1, 2, 'MjIcZGfDpn');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 55', 1, 2, 'bjtsnyAKRm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 56', 1, 2, 'yUtJwdTWGS');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 57', 1, 2, 'XHhqtDRsPL');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 58', 1, 2, 'APdYEstbcu');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 59', 1, 2, 'pyjRnAukhy');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 60', 1, 2, 'mWDgckKjDm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 61', 1, 2, 'nszQgTLkHL');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 62', 1, 2, 'pweuYBkTnp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 63', 1, 2, 'XIUkmQQlzs');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 64', 1, 2, 'lwtDmhYKob');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 65', 1, 2, 'iGHnnVumOQ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 66', 1, 2, 'zuLRgEYOtg');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 67', 1, 2, 'MrylNSsadZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 68', 1, 2, 'swwZVnrYMT');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 69', 1, 2, 'JCzfEqMUIF');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 70', 1, 2, 'iDnwqvXObh');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 71', 1, 2, 'avTBpJWoVt');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 72', 1, 2, 'uTCsegZynt');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 73', 1, 2, 'vjtDHFXMEg');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 74', 1, 2, 'OSWzWKwDpL');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 75', 1, 2, 'FKGqpjtCqW');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 76', 1, 2, 'ERDagsmUQN');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 77', 1, 2, 'PnFnEIkooc');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 78', 1, 2, 'wwYUjipxze');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 79', 1, 2, 'iJmOpIjQko');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 80', 1, 2, 'shCavVPkhb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 81', 1, 2, 'HkGByTGDBf');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 82', 1, 2, 'kjIHIpLGuT');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 83', 1, 2, 'koPuJcztNH');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 84', 1, 2, 'WUruulpSIi');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 85', 1, 2, 'qLaNycLqDD');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 86', 1, 2, 'qPDinKQJTJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 87', 1, 2, 'BmayPmLBkf');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 88', 1, 2, 'udNLfGmBBd');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 89', 1, 2, 'tsuwfnWcpb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 90', 1, 2, 'LbzoyZzKvb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 91', 1, 2, 'gacrhtufqr');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 92', 1, 2, 'btwlyoribX');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 93', 1, 2, 'LAvIehzpxX');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 94', 1, 2, 'zfDSrOmRxm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 95', 1, 2, 'PLEUvhHOtd');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 96', 1, 2, 'mOLLPwFqba');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 97', 1, 2, 'iAttafnnoB');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 98', 1, 2, 'tnGtDmpvvI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 99', 1, 2, 'FhdWTmvamo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 100', 1, 2, 'OayKQFmyYM');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 101', 1, 2, 'GhNVBvEmCz');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 102', 1, 2, 'UVxBJKNBzv');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 103', 1, 2, 'eHnFZMnwBq');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 104', 1, 2, 'aeUtZoBFvH');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 105', 1, 2, 'jbOCZlwXwk');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 106', 1, 2, 'bJVWbKFTVg');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 107', 1, 2, 'UvrjfDLaxb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 108', 1, 2, 'rGnlteUaaK');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 109', 1, 2, 'nDFNkjVnRU');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 110', 1, 2, 'bIKxiKrwff');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 111', 1, 2, 'PrwFusGeWR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 112', 1, 2, 'oRsudBOFom');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 113', 1, 2, 'RjKKAiWbQc');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 114', 1, 2, 'zjKZvQjZsS');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 115', 1, 2, 'kWjmGajHkL');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 116', 1, 2, 'exkJFUnZhV');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 117', 1, 2, 'NVjJgYYeYA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 118', 1, 2, 'AQIhYCFkNy');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 119', 1, 2, 'gTwuIPujZB');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 120', 1, 2, 'QfOfOHwzyI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 121', 1, 2, 'LuAPKWbXcZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 122', 1, 2, 'WafOHNAhRu');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 123', 1, 2, 'LvJsfAtsNB');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Charger MacBook Air 124', 1, 2, 'EfBxmhDGxZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 0', 1, 3, 'mOaJyVyEew');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 1', 1, 3, 'JNdEIOeuzZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 2', 1, 3, 'UQlqEwSJGR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 3', 1, 3, 'zMKPRLjeoV');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 4', 1, 3, 'AnRAmgkbbG');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 5', 1, 3, 'udipPHGZXt');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 6', 1, 3, 'YBWVBeDbfr');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 7', 1, 3, 'BmNpIfcdQZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 8', 1, 3, 'EoERfRaYEl');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 9', 1, 3, 'pqCmYAlIyx');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 10', 1, 3, 'HbSrEPZwOP');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 11', 1, 3, 'LgTuQlhfEC');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 12', 1, 3, 'wVbbSdzXJl');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 13', 1, 3, 'mxRJYiZbgb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 14', 1, 3, 'iQjDzlNAIo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 15', 1, 3, 'QeDFBeLxGd');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 16', 1, 3, 'kgcNibzuQY');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 17', 1, 3, 'gxVVJSsCvF');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 18', 1, 3, 'gCBzSxGdDp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 19', 1, 3, 'PmUmMvnLPX');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 20', 1, 3, 'hcgYyVNygU');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 21', 1, 3, 'VfNnYCGpHt');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 22', 1, 3, 'jQqhLcIIET');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 23', 1, 3, 'nYZROkJxoo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 24', 1, 3, 'iXGmVfxQkL');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 25', 1, 3, 'zHqSGNpxBt');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 26', 1, 3, 'yriQFEaHIc');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 27', 1, 3, 'oCKLypvCji');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 28', 1, 3, 'lCkEEfHgWy');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 29', 1, 3, 'lbzJFdZLDw');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 30', 1, 3, 'nuYGPbcHaw');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 31', 1, 3, 'MNXAtCNjPK');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 32', 1, 3, 'lchrEGOsPv');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 33', 1, 3, 'SmfSDTvnJb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 34', 1, 3, 'DLueKnmXwb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 35', 1, 3, 'NnqcbjHYnT');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 36', 1, 3, 'rfEVDjCdwj');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 37', 1, 3, 'uVjLuPDcOy');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 38', 1, 3, 'hBcKfgvntB');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 39', 1, 3, 'SIOtiMwrgk');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 40', 1, 3, 'GUlixcZoTp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 41', 1, 3, 'OLrNlRcPbT');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 42', 1, 3, 'ZwTCwmDvhP');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 43', 1, 3, 'SDddYJgkKj');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 44', 1, 3, 'AANDqbNaBU');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 45', 1, 3, 'WeBihazwUs');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 46', 1, 3, 'BmszLJHWzV');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 47', 1, 3, 'PSHXZHxfYJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 48', 1, 3, 'pZxtHxEGzq');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 49', 1, 3, 'qBXHAAeBMj');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 50', 1, 3, 'GKTSzeRuGQ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 51', 1, 3, 'JdTcvXwtRV');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 52', 1, 3, 'mzBwoYpLPy');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 53', 1, 3, 'AvHRkKXDUA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 54', 1, 3, 'hVXeMdgFFa');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 55', 1, 3, 'EWrelncuRQ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 56', 1, 3, 'ZvabfQJgjI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 57', 1, 3, 'rYKXaxJjRz');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 58', 1, 3, 'wxjNSeruZH');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 59', 1, 3, 'OxnDxuAoFY');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 60', 1, 3, 'PPYUKYHoDs');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 61', 1, 3, 'bcZngFVMSr');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 62', 1, 3, 'nzFFDULYuT');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 63', 1, 3, 'lXBKpLWJtj');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 64', 1, 3, 'asmnPNMcFq');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 65', 1, 3, 'EvUlAnfIHP');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 66', 1, 3, 'EjAUlaBcwD');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 67', 1, 3, 'yrLZqPEPFU');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 68', 1, 3, 'IefLAQMiid');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 69', 1, 3, 'kFhiYcMXHp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 70', 1, 3, 'EzoRjTWkiP');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 71', 1, 3, 'IltlAjpkNm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 72', 1, 3, 'qnvMBAaSpL');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 73', 1, 3, 'LWjYfDJXOp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 74', 1, 3, 'lpDRGEXpFI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 75', 1, 3, 'YgzKpLGZIj');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 76', 1, 3, 'ZWlivlyqRF');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 77', 1, 3, 'iEJDxkUjtK');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 78', 1, 3, 'ZJYfZDzUGQ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 79', 1, 3, 'FlAETfiDkX');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 80', 1, 3, 'bSlIwlXSbM');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 81', 1, 3, 'xEPipFfWgo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 82', 1, 3, 'tpTvmJrfLt');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 83', 1, 3, 'vlCZvTSlhk');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 84', 1, 3, 'pEheTMbfeK');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 85', 1, 3, 'yVGnubFhAi');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 86', 1, 3, 'shKBNFJUVI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 87', 1, 3, 'XstmhWzfBl');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 88', 1, 3, 'ZBJroZRmSJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 89', 1, 3, 'QvTZGsrCoV');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 90', 1, 3, 'RlgaujvyGA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 91', 1, 3, 'mJTnKATZrQ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 92', 1, 3, 'zfyFdOBpIA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 93', 1, 3, 'PQPDnXsWNF');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 94', 1, 3, 'mAfhTSboaI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 95', 1, 3, 'DYQquyptDk');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 96', 1, 3, 'RUoGNCThcl');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 97', 1, 3, 'xwIWSMDCnI');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 98', 1, 3, 'sdsKtAyigZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 99', 1, 3, 'UHQNibHKpV');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 100', 1, 3, 'zhlaUrzNyT');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 101', 1, 3, 'oFJHIBjFlo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 102', 1, 3, 'lpkNnjwjHE');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 103', 1, 3, 'qKzhTWOpGw');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 104', 1, 3, 'CJYTlpPHlX');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 105', 1, 3, 'lzDUnSFDGx');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 106', 1, 3, 'VvAcmYkUtv');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 107', 1, 3, 'WUjMVUSAqH');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 108', 1, 3, 'olaTIORiyu');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 109', 1, 3, 'tGfbSLFzwU');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 110', 1, 3, 'dNSwNGIUTR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 111', 1, 3, 'qKfMQgePQR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 112', 1, 3, 'McnlElcWIR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 113', 1, 3, 'ShyVLfLMxH');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 114', 1, 3, 'luqaxMCxBc');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 115', 1, 3, 'WTJPtAjMfb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 116', 1, 3, 'rZxaIKclCw');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 117', 1, 3, 'bbnLeLCSSm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 118', 1, 3, 'ivKLqbwUDD');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 119', 1, 3, 'VSupKhECHw');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 120', 1, 3, 'pZMniDahRx');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 121', 1, 3, 'JOVuXjXOYc');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 122', 1, 3, 'MTJQzBBmUf');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 123', 1, 3, 'ethurOJYKm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 124', 1, 3, 'GqwbHyAHvW');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 125', 1, 3, 'FlTwtopHiA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 126', 1, 3, 'bIaJAZCNKe');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 127', 1, 3, 'SDCvTMMbCm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 128', 1, 3, 'SzXlyTNXmi');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 129', 1, 3, 'HVGiPyCIvN');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 130', 1, 3, 'vKvBpYxQmr');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 131', 1, 3, 'DoiqFpGyXm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 132', 1, 3, 'OmoiUBJJmo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 133', 1, 3, 'pLEbFWYdqw');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 134', 1, 3, 'zXmuNfIQwb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 135', 1, 3, 'ugpsGdkfPg');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 136', 1, 3, 'nvJQHarEnY');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 137', 1, 3, 'KsOotRyUGa');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 138', 1, 3, 'AVijFWIitY');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 139', 1, 3, 'ufEztaJwvo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 140', 1, 3, 'BbOrJVJUzk');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 141', 1, 3, 'IwjDMEOOft');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 142', 1, 3, 'BDymyyIXbG');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 143', 1, 3, 'wKrUyFqpME');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 144', 1, 3, 'QrLbWzdnnJ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 145', 1, 3, 'qOPmZHPkYY');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 146', 1, 3, 'qjvkmckjCr');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 147', 1, 3, 'kNbvpaShEW');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 148', 1, 3, 'NwChLrDbzK');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 149', 1, 3, 'qscCIhKLOv');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 150', 1, 3, 'uIXYDozzKV');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 151', 1, 3, 'NppPADuvye');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 152', 1, 3, 'WBhqTeJnAC');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 153', 1, 3, 'HguNmPPQxe');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 154', 1, 3, 'LvrQwaUyrQ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 155', 1, 3, 'erxKAejBoy');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 156', 1, 3, 'mbPtTNrsjB');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 157', 1, 3, 'MDbTxrAtxb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 158', 1, 3, 'EFMzuPKAhz');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 159', 1, 3, 'xSWNLRdQMF');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 160', 1, 3, 'UTCfwluzlY');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 161', 1, 3, 'UoLgpCxKJL');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 162', 1, 3, 'lLBrzhamrw');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 163', 1, 3, 'DrRNZLScDV');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 164', 1, 3, 'ndgBwOECTi');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 165', 1, 3, 'SeEgxADWKA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 166', 1, 3, 'LLMGgWUwnD');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 167', 1, 3, 'uvqVJOHcoh');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 168', 1, 3, 'BljMSZbORT');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 169', 1, 3, 'GcZFJVofRQ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 170', 1, 3, 'mToyaZNeve');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 171', 1, 3, 'MEgkOmpNTp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 172', 1, 3, 'rpzmRNoiJg');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 173', 1, 3, 'lkeCVfmcwp');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 174', 1, 3, 'gbPYWtOZgm');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 175', 1, 3, 'xVtLblukyf');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 176', 1, 3, 'PROlLyxLHb');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 177', 1, 3, 'jYRFrpfHeK');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 178', 1, 3, 'qayPjajjCA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 179', 1, 3, 'fqSxGCtBiZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 180', 1, 3, 'nYbSsReLAe');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 181', 1, 3, 'MamaHvdNOZ');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 182', 1, 3, 'DXiDnzlQHc');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 183', 1, 3, 'vCscZRutle');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 184', 1, 3, 'QYVAjJvrmD');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 185', 1, 3, 'lLACkGDerT');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 186', 1, 3, 'ugqDDUqDNA');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 187', 1, 3, 'ZCLkKUFsGR');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 188', 1, 3, 'yrjuxDstyT');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 189', 1, 3, 'xGXteDOeEn');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 190', 1, 3, 'hXASxVDTRo');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 191', 1, 3, 'ioPQIqVbab');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 192', 1, 3, 'AzVIryYvMu');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 193', 1, 3, 'FIifGRoMur');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 194', 1, 3, 'moayGsBtiz');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 195', 1, 3, 'vHyroWCNBM');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 196', 1, 3, 'erntJuIxtg');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 197', 1, 3, 'pRDxhhllJY');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 198', 1, 3, 'JGBJUrqQtX');
INSERT INTO asset (asset_name, asset_quantity, asset_type_id, _id) VALUES ('Screen Dell 199', 1, 3, 'UctOVdWPhB');
